### ISSUE TITLE
Why are these operators not in Airflow as standards

### ISSUE THREAD

**Issue by KarthikRajashekaran** [tomasfarias/airflow-dbt-python#105]
Why are these operators not in Airflow as standards

Anything I am missing?

**Comment by KarthikRajashekaran** [comment]
We have a requirement to clone the GitLab repo dbtproject to airflow and run dbt operators 

Does airflow-dbt-python helps in this case?

We are using Airflow with K8s

**Comment by KarthikRajashekaran** [comment]
@tomasfarias Please check Airflow Slack messages , to see if someone can help you to get as standards in airflow

**Comment by tomasfarias** [comment]
> We have a requirement to clone the GitLab repo dbtproject to airflow and run dbt operators
> Does airflow-dbt-python helps in this case?

The `DbtGitRemoteHook` was built exactly to support dbt projects stored in git repositories. Granted, it's new in version 1.0, and I haven't had the chance to test it with GitLab. It would be very appreciated if you could test it out. If not, I can run some tests over the next week or so. Happy to address any issues that crop up.

The documentation contains an example DAG for downloading a dbt project GitHub: https://airflow-dbt-python.readthedocs.io/en/latest/getting_started.html#id7.

> Please check Airflow Slack messages , to see if someone can help you to get as standards in airflow.

I'm currently more focused on fixing bugs. However, we do want to support the Airflow provider interface, so PRs are more than welcome.

**Comment by KarthikRajashekaran** [comment]
Sure i will try to play around when i get chance 
Meanwhile i was able to clone gitlab repo using the bashoperator 

Now i want to use your operator DbtRunOperator to run dbt commands 

In local i go the dbtrepofolder to model directory and run below command , Can you provide example for the same using the operator 

`dbt run --profiles-dir ~/.dbt/ --target dev`
