### ISSUE TITLE
 The conn_id `fs_default` isn't defined

### ISSUE THREAD

**Issue by KarthikRajashekaran** [tomasfarias/airflow-dbt-python#111]
Airflow version : 2.5.2
Airflow runs in EKS
Installed dbt version 
```
dbt-core==1.4.5 
dbt-snowflake==1.4.1 
airflow-dbt-python[snowflake]

```
profiles.yml
```
abc_metrics:
  outputs:
    dev:
      account: abc
      database: DEV
      role: DBT-ROLE
      schema:ABC_METRICS
      threads: 1
      type: snowflake
      user: <first>.<last>@ABC.COM
      warehouse: WH_M
  target: dev

```

```
clone_repo = BashOperator(
       task_id='clone_repo',
       bash_command='git clone https://$gitlabUser:$gitlabToken@scm.platform.io/abc.git /opt/airflow/dbt/',
   )

   dbt_run = DbtRunOperator(
       task_id="dbt_run",
       project_dir="/opt/airflow/dbt/models",
       profiles_dir="~/.dbt/",
       select=["tag:staging"],
       exclude=["tag:deprecated"],
       target="dev",
       profile="profiles.yml",
       full_refresh=False,
       threads=100,
       fail_fast=True,
   )
```
```
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T12:39:22.474515+00:00
[2023-03-29, 12:39:43 UTC] {dbt.py:165} INFO - Running dbt task: run
[2023-03-29, 12:39:46 UTC] {dbt.py:319} INFO - Initializing temporary directory: /tmp/airflow_tmpne65x0vs
[2023-03-29, 12:39:46 UTC] {dbt.py:176} ERROR - An error has ocurred while executing dbt run
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 148, in get_remote
    return self.remotes[(scheme, conn_id)]
KeyError: ('', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 322, in dbt_directory
    project_dir, profiles_dir = self.prepare_directory(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 367, in prepare_directory
    project_dir_path = self.download_dbt_project(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 180, in download_dbt_project
    remote = self.get_remote(scheme, self.project_conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 150, in get_remote
    remote = get_remote(scheme, conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/remote.py", line 165, in get_remote
    remote = remote_cls()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/localfs.py", line 38, in __init__
    super().__init__(fs_conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
```

Also tried with airflow_conn_id , same error

**Comment by tomasfarias** [comment]
For a Production db deployment I'd refer you to the Airflow docs, as that goes beyond airflow-dbt-python: https://airflow.apache.org/docs/apache-airflow/2.5.2/administration-and-deployment/production-deployment.html

A bit contradictory, Airflow recommends not running `airflow db init`, but links to the documentation page on [setting up a database backend](https://airflow.apache.org/docs/apache-airflow/2.5.2/howto/set-up-database.html#initialize-the-database) which does run `airflow db init`.

Given the small contradiction, I think the decision is ultimately up to you: either run `airflow db init` after [setting up your database](https://airflow.apache.org/docs/apache-airflow/2.5.2/howto/set-up-database.html#initialize-the-database), or not and create a `fs_default` connection (refer to the [Connection docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html)).

**Comment by KarthikRajashekaran** [comment]
But our airflow db is external that is RDS , BTW i have sent you an email too about another issue which is 

no dbt_project.yml found at expected path /tmp/airflow_tmpgzobh886/dbt_project.yml

**Comment by tomasfarias** [comment]
> But our airflow db is external that is RDS

A simple search will reveal that the [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/2.5.2/howto/set-up-database.html#initialize-the-database) covers specific settings for Amazon RDS. I refer to you that as it's a much better resource than anything I can produce in a reasonable amount of time

**Comment by KarthikRajashekaran** [comment]
Thanks 

Should i raise new issue for below 
```no dbt_project.yml found at expected path /tmp/airflow_tmpgzobh886/dbt_project.yml```

**Comment by tomasfarias** [comment]
> BTW i have sent you an email too about another issue which is
> no dbt_project.yml found at expected path /tmp/airflow_tmpgzobh886/dbt_project.yml

I was getting to it, please have patience.

I would look into the following:

* Check if there is a `dbt_project.yml` in your repo. Specifically in the root directory.
* Check if you are using an Airflow Local Executor.
  * This DAG will not work with an Airflow Remote Executor (at least, not all the time and specially under load). The reasons for that are discussed in the [docs](https://airflow-dbt-python.readthedocs.io/en/latest/getting_started.html#accessing-a-dbt-project) (albeit briefly, docs could use some love).
  * This is the reason why we support dbt git remotes, maybe you should look into them. Since they are fairly new, documentation is scarce: here's an [example DAG](https://github.com/tomasfarias/airflow-dbt-python/blob/master/examples/dbt_project_in_github_dag.py), and here's the [API reference](https://airflow-dbt-python.readthedocs.io/en/latest/reference/hooks.html#module-airflow_dbt_python.hooks.git) for git remotes.

**Comment by KarthikRajashekaran** [comment]
We are using Airflow in EKS , which is Kubernetes executor 
There is dbt_project.yml in the path 
<img width="348" alt="image" src="https://user-images.githubusercontent.com/33160284/228704312-08b72cb5-d06a-406c-ad63-022fcee79fde.png">

**Comment by tomasfarias** [comment]
> We are using Airflow in EKS , which is Kubernetes executor

That would explain why the DAG doesn't work.

**Comment by KarthikRajashekaran** [comment]
> > We are using Airflow in EKS , which is Kubernetes executor
> 
> That would explain why the DAG doesn't work; Kubernetes executor is a form of [remote executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/index.html#executor-types).

So we cannot use your operator in the Kubernetes

**Comment by tomasfarias** [comment]
> So we cannot use your operator in the Kubernetes

You can, as I have stated before:

> This is the reason why we support dbt git remotes, maybe you should look into them.

**Comment by KarthikRajashekaran** [comment]
But using git remotes will zip the folder into s3 as per the dbtrunoperator , Right?

**Comment by tomasfarias** [comment]
No, git remotes work with git, not S3. Nothing will be uploaded or downloaded to or from S3.

**Comment by KarthikRajashekaran** [comment]
So will it work with gitlab too ?

Also, i updated the path where dbt_project.yml is located and it ran and new error 

```
  raise DbtProfileError(msg, result_type="invalid_target")
dbt.exceptions.DbtProfileError: Runtime Error
  The profile 'product_metrics' does not have a target named 'default'. The valid target names for this profile are:
   - target
   - dbt_conn_id
   ```

**Comment by tomasfarias** [comment]
> So will it work with gitlab too ?

Yup. Also with SourceHut and Gitea. Pretty much any git server accessible via http or ssh.

**Comment by tomasfarias** [comment]
> Updated to dag to include target='dev' and the above issue got resolved

I really doubt the above issue is resolved, you are just failing in a different place. DAG will never work with remote executors.

**Comment by tomasfarias** [comment]
This issue has de-railed for too long into a 1:1 free support session. Of course, paid support is an option if your company is willing.

Until then, my recommendation stands: try git remotes and report any issues with them or gaps in the documentation.
