### ISSUE TITLE
printer_width is None

### ISSUE THREAD

**Issue by driadi** [tomasfarias/airflow-dbt-python#129]
Hey team, I could be wrong but v2.0.0 may accidentally set dbt `flags.PRINTER_WIDTH` to None and this breaks other dbt packages that I am using in my environment.

**Comment by tomasfarias** [comment]
Looking at the dbt code (and in particular [this comment](https://github.com/dbt-labs/dbt-core/blob/719a50cc91bc7a2a219b6fa4209e892f14177eb6/tests/unit/test_context.py#L434)), it seems it should be fairly safe to set `printer_width` to default to 80.

**Comment by tomasfarias** [comment]
Have you tried setting printer_width manually? I.e. via an environment variable? I'm curious what happens then.

Maybe this could be hiding an underlying bug somewhere else, but it seems like a quick and easy fix to work with other packages. Happy to set the default while we investigate a bit further.

**Comment by driadi** [comment]
Yeah tried setting it manually but does not work. I think you need to set the default `80` in this [line](https://github.com/tomasfarias/airflow-dbt-python/blob/5cd7863f4ec851fc0c574c301b8e5105d8c78957/airflow_dbt_python/utils/configs.py#L127)

**Comment by tomasfarias** [comment]
Yup, that's what I'm doing (see linked PR). It should be set-able though, so wanted to investigate further...

**Comment by tomasfarias** [comment]
Will merge the PR regardless, thanks for your input!

**Comment by driadi** [comment]
Thanks @tomasfarias !
