### ISSUE TITLE
No module found dbt.semver

### ISSUE THREAD

**Issue by savilea** [tomasfarias/airflow-dbt-python#135]
Hi

I tried running with dbt-core 1.8 yesterday on MWAA and ran into No module name 'dbt.semver'... has any integration testing been done yet for dbt-core 1.8?.. Do you know when the release will happen?

**Comment by ydh4481** [comment]
in dbt-core 1.8 version release_note,
_Move dbt.semver to dbt.common.semver and update references_. <<

https://mygit.osfipin.com/release/154972909
