### ISSUE TITLE
dbt docs create not available

### ISSUE THREAD

**Issue by crisdo98** [tomasfarias/airflow-dbt-python#26]
Love this repo.. thanks for all your hard work. Is there a technical reason why the docs command has been omitted?

**Comment by tomasfarias** [comment]
Thanks for your comment! Feedback is very welcome as our use cases are limited compared to the huge amount of things we can do with dbt in Airflow.

I initially did not include docs as we had no way to export the documentation artifacts (`target/manifest.json`, `target/catalog.json`, and `target/index.html`). But after we added some XCom support, and with some touches to support pushing them to S3, I think this should now work!. I'm doing some work over in this branch: https://github.com/tomasfarias/airflow-dbt-python/tree/support-for-dbt-docs and will release it in the next minor version.

**Comment by crisdo98** [comment]
Thanks so much for this Tom. Amazing work!
