### ISSUE TITLE
Support for vars as a template_field

### ISSUE THREAD

**Issue by marcusintrohive** [tomasfarias/airflow-dbt-python#39]
Hey! Great package so far. Wondering about supporting vars as a templated_field. Looking to be able to use the dag_conf to pass different vars when running various dbt commands.

**Comment by tomasfarias** [comment]
Hello! Thanks for the comments!

I don't see why not support this, thanks for the suggestion; a PR is welcome, otherwise, I'll pick this one up later.

**Comment by tomasfarias** [comment]
Closed in #41. Thanks @marcusintrohive for the PR!
