### ISSUE TITLE
Connection failures cause an UnboundLocalError

### ISSUE THREAD

**Issue by tomasfarias** [tomasfarias/airflow-dbt-python#49]
When timing out attempting to connect to a database, dbt log a `DatabaseError`, like so:

```
Database Error
  connection to server at "<server>" (<ip>), port <port> failed: timeout expired
```

dbt must be doing some under the hood exception handling as this is causing the `results` variable here: https://github.com/tomasfarias/airflow-dbt-python/blob/master/airflow_dbt_python/hooks/dbt.py#L580 to be unbound.

We should account for the possibility of no results/results being unbound.

**Comment by swong28** [comment]
I keep getting this error when setting up a dbt build task in MWAA with redshift. Do you have any idea what is causing this issue? 

The dbt profile is tested locally and is able to connect to redshift successfully locally.
