### ISSUE TITLE
Not all default arguments are being passed to the DbtBuildOperator

### ISSUE THREAD

**Issue by marcusintrohive** [tomasfarias/airflow-dbt-python#51]
Hey!

I noticed that the on_failure_callback from the default argument is not being passed to the DBTBuildOperator as wall as the sla argument.

I can see from the "Instance Details" these arguments are being passed to my other tasks but not to the airflow_dbt_python operators I bring in. Will try and come up with a PR for the fix, but if you have any guidance on where to start that would be great!

Thanks

**Comment by tomasfarias** [comment]
For the record, we are running Airflow 2.2.2, and the latest `airflow_dbt_python`.

**Comment by tomasfarias** [comment]
Interesting, we don't really have any tests that cover the `@dag` decorator or the TaskFlow API, so it could be something related to that specific syntax. I'll write a separate issue to include some tests that cover these APIs to see if we can reproduce the issue.

In the meantime, I'd suggest upgrading to `airflow-dbt-python 0.13.2`, and/or helping by providing a sample DAG for me to reproduce the issue.

Thank you!

**Comment by tomasfarias** [comment]
This issue hasn't been active in a while and as we have added further test coverage for the `@dag` TaskFlow API, I assume this issue is good to close.

If any new information crops up a new issue can be opened, and we will take a look again.
