### ISSUE TITLE
Airflow MWAA not able to install Spark Adapter

### ISSUE THREAD

**Issue by peixotoandrei** [tomasfarias/airflow-dbt-python#63]
Hi @tomasfarias and thanks for the awesome lib!

I am having some trouble using `airflow-dbt-python` in a project which uses a spark adapter to connect to an AWS EMR instance. Its mostly related to the inability to install the `dbt-spark[PyHive]` in MWAA (Airflow version 2.0.2).  `airflow-dbt-python` was installed without version specification in requirements.

I tried installing it through the `airflow-dbt-python[snowflake,postgres,redshift,bigquery, spark]` semantic at the requirements file, and also 
`airflow-dbt-python[all]` which actually threw an error saying there was no "'all' option for extras". Aside from that, it works as intended with other backend adapters. Is there any way to use it with Spark adapter?

Thanks for the attention!

**Comment by peixotoandrei** [comment]
Adding some context, below there is the Airflow MWAA Scheduler requirements.install log, filtered for "dbt":

![image](https://user-images.githubusercontent.com/92543625/169429901-66c995ee-c503-4c5a-89ac-85d7ff867dae.png)

**Comment by tomasfarias** [comment]
Hey @peixotoandrei, thanks for checking out `airflow-dbt-python` and opening an issue.

The `spark` extra is indeed not included in `airflow-dbt-python`, you can actually check out which extras we include in the project's [pyproject.toml](https://github.com/tomasfarias/airflow-dbt-python/blob/master/pyproject.toml#L233=). We provide extras for the adapters just as a convenience, and I originally added just four as those are the ones I was using at the time. There should be no compatibility issues with `dbt-spark`, it was just omitted as an extra as I was not using at the time.

For this reason, you can just install the adapter separately, for example, your `requirements.txt` could look like:

```
dbt-spark[PyHive]==1.1.0
airflow-dbt-python[redshift]==0.14
```

And the adapter should be available for `airflow-dbt-python` and `dbt` to use.

All this being said though, I'm not against adding `dbt-spark` as an additional extra, so I can get that going in a new patch. However, I can't provide different versions of `dbt-spark` as different extras, so it's likely that the patch will only add plain `dbt-spark` and any extras (`PyHive`, `ODBC`, `session`) will still need to be installed separately. Of course, we could replicate the extras from `dbt-spark` but I am not a fan of the additional maintenance burden of having to keep up with any extras updates in `dbt-spark`.

At least having `dbt-spark` as a dependency should ensure no dependency conflicts.

**Comment by tomasfarias** [comment]
I've closed this issue as stated in my previous comment. `dbt-spark` is now offered as an extra via `airflow-dbt-python[spark]`. However, if requiring any of `dbt-spark`'s extra I would still recommend to install both separately.

If you have any more issues, feel free to open a new issue, or comment here and I can consider re-opening.
