### ISSUE TITLE
dbt_run_operation operator fails with no arg

### ISSUE THREAD

**Issue by samLozier** [tomasfarias/airflow-dbt-python#65]
I have a macro that I can trigger from the cli with no arguments however it fails when triggered from airflow via the DbtRunOperation operator. Is this expected behavior?

The error I get in the airflow logs is `ERROR - 20:54:11  Encountered an error while running operation: a string or stream input is required `

**Comment by tomasfarias** [comment]
Hey @samLozier, thanks for reporting this issue. I tested it out and indeed I've reproduced the same scenario.

I quickly was able to identify a bug in the default argument for the `args` parameter of run-operation. I've fixed that in #66, as well as added a unit test that catches the bug. Once tests are green I'll cut release v0.14.5 with the patch.

**Comment by samLozier** [comment]
Thanks @tomasfarias !
