### ISSUE TITLE
airflow-dbt-python 0.15.0 does not provide the extra 'amazon'

### ISSUE THREAD

**Issue by zoltanctoth** [tomasfarias/airflow-dbt-python#80]
Hi, 

As per [the documentation](https://tomasfarias.github.io/airflow-dbt-python/getting_started.html#id2), Amazon can be installed by adding the `amazon` extra. Even though it seems it is not supported anymore?

```
➜  pip install airflow-dbt-python[redshift,amazon]
WARNING: airflow-dbt-python 0.15.0 does not provide the extra 'amazon'
```

**Comment by tomasfarias** [comment]
Hi @zoltanctoth!

Thanks for pointing this out.

Installing the extra is still supported. At some point we [updated the extra to `airflow-providers`](https://github.com/tomasfarias/airflow-dbt-python/blame/master/pyproject.toml#L236). However, the documentation was missing this change.
