### ISSUE TITLE
Rename dbt InternalException with DbtRuntimeError

### ISSUE THREAD

**Issue by marianore-beepboop** [tomasfarias/airflow-dbt-python#91]
As of last version of dbt-core (1.4.1), InternalException has been renamed to DbtRuntimeError and I'm not able to use this lib.
Changelog: https://github.com/dbt-labs/dbt-core/commit/eb200b46877c31469f410b7d47dfd245473ed7cb

**Comment by tomasfarias** [comment]
Thanks for reporting this and pointing me to the source @marianore-beepboop. I'll release v0.15.3 to fix this.
